spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:review_canvas_db;MODE=MySQL;

  jpa:
    open-in-view: false
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
