spring.application.name: review-back

spring:
  profiles:
    active: ${profile}
  config:
    import:
      - db.yml
      - scheduler.yml
  jwt:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWp1bm8tc3ByaW5nLWJvb3Qtc2VjdXJpdHktanByaW5nLWJvajdXJjdByaW5nLWJvb3Qtc2
    access-token-validity-time: 1h
    refresh-token-validity-time: 14d
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

aws:
  credentials:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_ACCESS_KEY}
  s3:
    bucket: romantic-pipe-review-bucket
  region:
    static: ap-northeast-2
