spring.application.name: review-back

spring:
  profiles:
    active: ${profile}
  config:
    import:
      - file:./domain-module/db.yml
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-in-seconds: 86400 #1일
    refresh-token-validity-in-seconds: 604800 #7일
    access:
      expiration: 100
      header: Authorization
    refresh:
      expiration: 200
      header: Authorization-refresh
