spring.application.name: review-back

spring:
  profiles:
    active: ${profile}
  config:
    import:
      - db.yml
  jwt:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWp1bm8tc3ByaW5nLWJvb3Qtc2VjdXJpdHktanByaW5nLWJvajdXJjdByaW5nLWJvb3Qtc2
    access-token-validity-time: 1h
    refresh-token-validity-time: 14d
