name: push image and deploy to aws

on:
  push:
    branches: [ "main", "develop" ]

env:
  JDK_VERSION: 17

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: review-canvas/gh-actions/common/jvm@main
        with:
          version: ${{ env.JDK_VERSION }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with jib
        uses: review-canvas/gh-actions/common/build/jib@main
        id: build-image
        with:
          target_module: api-module
          with_test: false
          repository: ${{ secrets.AWS_ECR_REPOSITORY }}
          tags: ${{ github.sha }}

      - uses: review-canvas/gh-actions/deploy/ecs@main
        with:
          ecs_cluster: ${{ vars.ECS_CLUSTER }}
          service: ${{ vars.ECS_SERVICE_API }}
          image: ${{ steps.build-image.outputs.image }}
