name: Build and analyze

on:
  push:
    branches: [ 'develop', 'main' ]
  pull_request:

env:
  JDK_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}
          cache: 'gradle'

      - name: Checkout Sonar cloud
        uses: review-canvas/gh-actions/common/sonar@main
        with:
          fetch-depth: 0
          owner: 'backend'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and analyze
        run: ./gradlew build sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_BACKEND_TOKEN }}
